### ISSUE TITLE
TypeError: null is not an object (evaluating 'i[0].match(/:(.*?);/)[1]')

### ISSUE THREAD

**Issue by StrongerLph** [Donaldcwl/browser-image-compression#36]
I caught this error while using the library to compress 8M images：

TypeError: null is not an object (evaluating 'i[0].match(/:(.*?);/)[1]')

May I ask why there is such a mistake?How can I solve this problem?

**Comment by Donaldcwl** [comment]
Would you mind to upload the image so that I can reproduce it?

**Comment by maxefi** [comment]
loading this image: , on `iPad air 2, ios 13.4.1, Chrome 81.0.4044.124` leads to an error:
```
Objects are not valid as a React child (found: TypeError: null is not an object (evaluating 'a[0].match(/:(.*?);/)[1]')). If you meant to render a collection of children, use an array instead.
```

can not reproduce it on any other browser/device so far.

**Comment by Donaldcwl** [comment]
@maxefi Thanks for the follow-up. I don't have any Apple device in hand so I cannot reproduce it.
I wrote a debugging version of this lib:
[browser-image-compression.zip](https://github.com/Donaldcwl/browser-image-compression/files/4722579/browser-image-compression.zip)

Can you use this script to run on your devices?

**Comment by defigor** [comment]
@Donaldcwl Thanks very much for providing support for this issue. We've tried to use it on this device with the provided debugging version, it doesn't give any extra information. The error still is:
TypeError: null is not an object (evaluating 'arr[0].match(/:(.*?);/)[1]')
Do you want to provide any other version with more extensive logging?

**Comment by maxefi** [comment]
@Donaldcwl what are your thoughts on the issue? any possible workaround coming any soon?

**Comment by florian-milky** [comment]
Same issue here

**Comment by florian-milky** [comment]
I tried to set a `maxWidthOrHeight` hoping it would solve the issue, which it did, but then the image was all black

**Comment by raccoonback** [comment]
I agree with the @defor comment. 😃😃

Because there is a [`maximum canvas size`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size) supported by each browser, I think the image size should be limited to the [`maximum canvas size`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size) for each browser, not `Number.POSITIVE_INFINITY`.

When I tested Safari with a larger image than 268,435,456 pixels (i.e., 16,384 x 16,384), an error occurred as shown in the picture below.

<img width="1419" alt="스크린샷 2021-07-20 오전 1 49 59" src="https://user-images.githubusercontent.com/16451031/127628162-9642e1c8-d23e-4b46-b91e-9e707b715e20.png">


What do @Donaldcwl think about limiting the image to the maximum size supported by each browser?

ref.
- [HTMLCanvasElement.toDataURL()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)
- [maximum-size-of-a-canvas-element](https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element)

**Comment by Donaldcwl** [comment]
fixed in v1.0.15

**Comment by troymeyer1** [comment]
I’m still having this issue with v1.0.15 on iPhones. Guessing it’s a memory issue?

**Comment by taoliujun** [comment]
still appear with v1.0.17 on ios 13.0
